name = "clash-filter-api"
main = "src/index.js"
compatibility_date = "2023-05-18"

[observability.logs]
enabled = false

[vars]
DEFAULT_URL = "https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml"

[build]
command = "npm install"
